### ISSUE TITLE
[Feature Request] Local activities

### ISSUE THREAD

**Issue by josh-berry** [temporalio/omes#102]
Make sure we support generating/running workloads with local activities. Local activities have some differences vs. regular activities that we should make sure we cover (e.g. how slot allocation happens).

**Comment by Sushisource** [comment]
They're already supported just fine. EX On the workflow side: https://github.com/temporalio/omes/blob/403d0cc3688e9787da65a2cc2bd79350a7b9fd24/workers/go/kitchensink/kitchen_sink.go#L206

And the fuzzer can generate them here https://github.com/temporalio/omes/blob/3f0fa02e870ef2ab92e683bff7b1fd740a046e07/loadgen/kitchen-sink-gen/src/main.rs#L548
